# Generated by Django 6.1.2 on 2026-10-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecredit',
            name='source_page_url',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(fields=('product', 'path'), name='unique_image_path_per_product'),
        ),
    ]
