# Generated by Django 6.1.2 on 2026-10-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_imagecredit_source_page_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecredit',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
