"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
_env_file = BASE_DIR.parent / ".env"
if _env_file.exists():
    environ.Env.read_env(_env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#
# A `.env.example` copied verbatim deploys cleanly and runs on a committed key,
# which would let anyone forge an access token or sign a session cookie. Refuse
# to start on the placeholder (`SEC-FIND-1.1` in `docs/04-delivery/SECURITY-REVIEW.md`).
_PLACEHOLDER_SECRET_KEY = "change-me"


def require_real_secret_key(value: str) -> str:
    if value == _PLACEHOLDER_SECRET_KEY:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY is still the .env.example placeholder. Generate one with:\n"
            '  python -c "import secrets; print(secrets.token_urlsafe(48))"'
        )
    return value


SECRET_KEY = require_real_secret_key(env("DJANGO_SECRET_KEY"))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=False)
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS")
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS")
CORS_ALLOW_CREDENTIALS = True

# Transport and browser hardening (`SECURITY-REVIEW.md`). Inert while DEBUG is
# on, so local http development over compose is unaffected; in production the API
# is served over TLS by the host, which terminates and forwards the scheme.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 0 if DEBUG else 365 * 24 * 60 * 60
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
X_FRAME_OPTIONS = "DENY"

# Rate limits for the endpoints an anonymous caller can hit freely
# (`SEC-FIND-3.1`). Django Ninja parses "<count>/<period>"; the period is one of
# s, m, h, d. The E2E suite raises these so many users can register from a single
# address — see E2E-TEST-PLAN.md §5.
THROTTLE_LOGIN_RATE = env("THROTTLE_LOGIN_RATE", default="10/5m")
THROTTLE_REGISTER_RATE = env("THROTTLE_REGISTER_RATE", default="30/h")

# The host terminates TLS and forwards exactly one proxy hop, so the client
# address is the last X-Forwarded-For entry. Ninja uses this to key the throttles.
NINJA_NUM_PROXIES = env.int("NINJA_NUM_PROXIES", default=1)

# Caching (`ADR-0013`). Catalog reads are cached in `catalog/cache.py`, and the
# rate limits above are counted here. Both are per process — correct for the
# single-worker free tier, and the reason the two share this setting: pointing
# CACHE_URL at a shared backend (`redis://…`) fixes both at once.
CACHE_URL = env("CACHE_URL", default="")
if CACHE_URL:
    CACHES = {"default": env.cache_url("CACHE_URL")}
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "nordvik",
        }
    }

AUTH_USER_MODEL = "accounts.User"

# JWT authentication (access + refresh) — see ADR-0003.
# Falls back to DJANGO_SECRET_KEY. An empty value counts as unset, so a stray
# `JWT_SECRET_KEY=` cannot silently sign tokens with an empty secret.
JWT_SECRET_KEY = env("JWT_SECRET_KEY", default="") or SECRET_KEY
ACCESS_TOKEN_TTL_SECONDS = 15 * 60
REFRESH_TOKEN_TTL_SECONDS = 14 * 24 * 60 * 60
REFRESH_COOKIE_NAME = "nordvik_refresh"
REFRESH_COOKIE_SECURE = not DEBUG

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "accounts",
    "core",
    "catalog",
    "cart",
    "orders",
    "payments",
]

MIDDLEWARE = [
    # First, so every log line emitted further down the stack carries the id.
    "core.middleware.RequestIDMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": env("POSTGRES_HOST"),
        "PORT": env("POSTGRES_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"


# Logging — one JSON object per line, each tagged with the request id.

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {"request_id": {"()": "core.logging.RequestIDFilter"}},
    "formatters": {"json": {"()": "core.logging.JsonFormatter"}},
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
            "filters": ["request_id"],
        },
    },
    "root": {
        "handlers": ["console"],
        "level": env("DJANGO_LOG_LEVEL", default="INFO"),
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}
